function __dict() {
  let obj = [
    { key: "creator", value: "创建者" },
    { key: "owner", value: "所有者" },
    { key: "admin", value: "管理员" },
    { key: "blocked", value: "被屏蔽" },
    { key: "reviewer", value: "审核者" },
    { key: "executor", value: "负责人" },
    { key: "member", value: "成员" },
    { key: "unconfirmed", value: "待审核" },
    { key: "marster", value: "支持者" },
    { key: "external", value: "外部成员" },
    { key: "project", value: "项目" },
    { key: "create", value: "创建" },
    { key: "order", value: "排序" },
    { key: "delete", value: "删除" },
    { key: "name", value: "名字" },
    { key: "description", value: "摘要" },
    { key: "type", value: "类型" },
    { key: "cover", value: "封面" },
    { key: "default_version", value: "默认版本" },
    { key: "remove_version", value: "移除版本" },
    { key: "chat_service", value: "通讯服务" },
    { key: "invite_uris", value: "邀请加入" },
    { key: "jsonContent", value: "主体内容" },
    { key: "overview", value: "概览" },
    { key: "media", value: "预览" },
    { key: "start", value: "起始日期" },
    { key: "end", value: "结束日期" },
    { key: "deadline", value: "交付时间" },
    { key: "board", value: "工作空间" },
    { key: "group", value: "分组" },
    { key: "status", value: "状态" },
    { key: "icon", value: "图标" },
    { key: "kanban", value: "看板" },
    { key: "title", value: "标题" },
    { key: "column", value: "分栏" },
    { key: "card", value: "卡片" },
    { key: "followed_bies", value: "关注" },
    { key: "importance", value: "重要度" },
    { key: "urgency", value: "紧急度" },
    { key: "score", value: "分值" },
    { key: "color_marker", value: "颜色标签" },
    { key: "private", value: "设置私有" },
    { key: "card_todogroups", value: "卡片待办分组" },
    { key: "card_todo", value: "卡片待办" },
    { key: "card_storage", value: "卡片存储" },
    { key: "todogroups", value: "待办分组" },
    { key: "todo", value: "待办" },
    { key: "content", value: "内容" },
    { key: "role", value: "角色" },
    { key: "card_document", value: "卡片文档" },
    { key: "sub_folders", value: "子文件夹" },
    { key: "author", value: "作者" },
    { key: "storage", value: "网盘" },
    { key: "modify", value: "修改" },
    { key: "read", value: "读取" },
    { key: "manageMember", value: "管理成员" },
    { key: "manageRole", value: "设置权限" },
    { key: "create_version", value: "新增版本" },
    { key: "files", value: "文件" },
    { key: "mm_channel_id", value: "聊天频道" },
    { key: "preferences", value: "偏好设置" },
    { key: "document", value: "文档" },
    { key: "schedule_event", value: "规划事件" },
    { key: "schedule_events", value: "规划事件" },
    { key: "subject", value: "事件内容" },
    { key: "location", value: "地点" },
    { key: "time", value: "时间" },
    { key: "share", value: "分享" },
    { key: "schedule", value: "规划" },
    { key: "card_schedule", value: "任务规划" },
    { key: "card_schedule_event", value: "任务规划事件" }
  ];
  return obj;
}

export { __dict };

export function to_CN(key) {
  let __ = __dict();
  return __.find((i) => i.key === key).value;
}
