name: Build and Release
on:
  push:
    branches:
      - main  # 或者你想要自动构建的分支

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  # 或者你的项目所需的Node.js版本

      - name: Install dependencies
        run: npm ci  # 或者使用yarn

      - name: Build IPBase app
        run: npx quasar build -m electron  # 运行quasar build命令

      - name: Release app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
